name: MysteryHunt
version: 1.0.0
author: MrMarshall
api-version: 1.13
website: https://mrmarshall.dev/
softdepend: [PlaceholderAPI, ProtectionStones, WorldGuard, WorldEdit]
main: dev.mrmarshall.mysteryhunt.MysteryHunt

commands:
  huntingtool:
    description: Gives you the Huntingtool

permissions:
  mysteryhunt.huntingtool:
    default: op
    description: Permission for /huntingtool command
  mysteryhunt.*:
    default: op
    children:
      mysteryhunt.huntingtool: true